services:
  web:
    build:
      context: .
      target: production-proxy-stage
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
  dev:
    build:
      context: .
      target: development-stage
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      "__VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS": "${HOSTNAME}"

  prod:
    build:
      context: .
      target: production-stage
    image: registry.tompaton.com/tompaton/wfhcalendar
    profiles:
      - 'prod'
