version: '3'
services:
  www:
    image: registry.tompaton.com/tompaton/wfhcalendar-server
    networks:
      - www
    env_file:
      - production.env
    volumes:
      - /var/data/tom/wfhcalendar/data:/data
    restart: unless-stopped

networks:
  www:
    external:
      name: www
