name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Docker Setup Compose
      uses: docker/setup-compose-action@v1.2.0
          
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker compose --profile prod build
        docker compose --profile prod push

    - name: Copy production files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "production.env,production.yml"
        target: /var/data/wfhcalendar.tompaton.com/

    - name: Deploy on server
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/data/wfhcalendar.tompaton.com
          docker-compose -f production.yml pull
          docker-compose -f production.yml up -d
